### ISSUE TITLE
Retrying requests using backoff for API/web requests

### ISSUE THREAD

**Issue by zappybiby** [xxxFRIARxxx/SaltyBot#13]
**Is your feature request related to a problem? Please describe.**
It may be beneficial for us to use the [backoff library](https://pypi.org/project/backoff/) to handle retrying failed requests and implement an exponentially increasing wait time between failed requests. I think that the python `backoff` library may be useful as it provides function decorators that could handle retrying failed Twitch API or SaltyBet state.json requests, with options for  constant/exponentially increasing wait times until successful response is received.

### Native
If we wanted to use the requests library natively, this [stackoverflow post](https://stackoverflow.com/a/35504626) shows a way we can use `HTTPAdapter` from `requests.adapters` to handle retries.

### Using backoff library
Uses exponential backoff for retries when request exception occurs, prints to console on each retry, and attempts 10 retries before giving up and raising exception.
```
def backoff_hdlr(details):
    print ("Backing off {wait:0.1f} seconds after {tries} tries "
           "calling function {target} with args {args} and kwargs "
           "{kwargs}".format(**details))

@backoff.on_exception(backoff.expo,
                      requests.exceptions.RequestException,
                      on_backoff=backoff_hdlr,
                      max_tries=10)
def get_url(url):
    return requests.get(url)
```

**Comment by xxxFRIARxxx** [comment]
Hey Zappy:

Would you like to work on this for me?  I'd like to use the Native approach you'd listed above if possible.

You don't have to by any means.  I just figured I'd ask because I've turned my attention to a completely different project for the time being.

If not, I'll get around to this eventually.  For now, I have the JSON exception throwing for us so we can catch exactly where it's returning None.

**Comment by zappybiby** [comment]
I did some stress tests with the SB website, even requesting content constantly didn't produce any invalid responses.

My thought process with implementing backoff is that I thought that this occasional JSON error might be the result of hitting an API request limit of some sort, or maybe the CDN was blocking our requests temporarily. But it doesn't seem like that's the case from my testing.

I will close this as it seems our 1 second delays between refreshing/requesting session seem sufficient for now.
