### ISSUE TITLE
Kelly suggested bet overriding default all-in bet for Tournament mode  

### ISSUE THREAD

**Issue by zappybiby** [xxxFRIARxxx/SaltyBot#14]
**Describe the bug**
In Tournament mode, it looks like the kelly criterion suggest bet logic is overriding the default all-in strategy used for Tournament mode if under 20000. 

**Example**
```
Currently in Tournament with 6 matches remaining.  Game state is open.
+-----------+---------+-------------+----------+
|  Fighter  |   Skill |   Variation |   Streak |
+===========+=========+=============+==========+
| Player 1: | 29.3958 |     7.17148 |        2 |
+-----------+---------+-------------+----------+
| Player 2: | 29.3958 |     7.17148 |        3 |
+-----------+---------+-------------+----------+
Player 1 chance to win: 50.0%
Current Balance is: $1,450
Bet placed: $1 on player2
Current Tier is: 2
```
suggested_bet follows k_suggest instead of the tournament logic:
```
        if (game_mode == "Tournament") and (self.balance < 20000):
            suggested_wager = self.balance
```
because of [this](https://github.com/xxxFRIARxxx/SaltyBot/blob/main/SaltyBettor.py#L96) statement

**Comment by zappybiby** [comment]
That `elif (predicted_winner != None)` might also cause problems with the all-in behavior for matchmaking when balance > 10000

**Comment by xxxFRIARxxx** [comment]
This has either been corrected in a commit past the one in your current fork (which is 2 commits behind my main), or I've recently fixed this (as of last night / today) in mine, and just haven't pushed a commit yet.  

Will be shortly.
