### ISSUE TITLE
Session Headers are overwritten to default values in SaltyJson 

### ISSUE THREAD

**Issue by zappybiby** [xxxFRIARxxx/SaltyBot#16]
I think I may have discovered something

#### It seems our headers for the requests.Session() aren't actually being changed to `User-Agent": "Mozilla/5.0", "Accept":"application/json` as we want it to in our GET request. Instead, I found that they were still the python requests default, 
```
output of print(self.session.headers) in SaltyJson:
{'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}
```
If I'm correct, then the headers provided in 

`self.response = self.session.get(self.url, headers={"User-Agent": "Mozilla/5.0", "Accept":"application/json"})`

are not actually persisting with each GET request of our session!

I was reading the [advanced usage section](https://requests.readthedocs.io/en/latest/user/advanced/) of the requests library docs, and saw this: 

"_Any dictionaries that you pass to a request method will be merged with the session-level values that are set. The method-level parameters override session parameters. Note, however, that method-level parameters will not be persisted across requests, even if using a session._"

So the provided headers dict is being overwritten by default header values -- they aren't persisting in the session. It looks like we have to use `self.session.headers.update` to have the provided headers persist in the active session!

#### Adding `self.session.headers.update({"User-Agent": "Mozilla/5.0", "Accept":"application/json"})` to `__init__` of SaltyJson:
```
def __init__(self):
    self.url = "https://www.saltybet.com/state.json"
    self.session = requests.Session()
    self.session.headers.update({"User-Agent": "Mozilla/5.0", "Accept":"application/json"})
```
```
output of print(self.session.headers):
{'User-Agent': 'Mozilla/5.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive'}
```
My hope is that with these headers being properly set for the session, we may be one step closer to fixing #5?

**Comment by zappybiby** [comment]
My attempt to fix: https://github.com/zappybiby/SaltyBot/commit/d6eb3a7fe811c29b863c83f9cd95a924d39546b5
Header persistence is fixed with this branch. I am fairly confident this is going to resolve the empty response causing JSONDecodeError as well, but going to run it for some time to see first. I'm not brave enough to PR yet.

**Comment by xxxFRIARxxx** [comment]
Honestly, I've had this program running for over 48 hours now with no errors on my end...but I'm SUPER stoked you've actually found they don't persist, and will be trying this out on my end too.  

PR when you're ready, or I'll let you know if I've done something different (or implemented it sooner than your PR) if that happens.

Thanks again!
