### ISSUE TITLE
Matches not being added to database

### ISSUE THREAD

**Issue by zappybiby** [xxxFRIARxxx/SaltyBot#2]
## Describe the bug
After result of match, program will attempt to store entry in database, but will fail to do so, instead returning the following error: ` table SBMATCHES has no column named betOutcome `. In addition, Matches following the failed attempt are also not stored/recorded in the database, but no additional errors are returned.
## To Reproduce
Start program for first time (delete existing SaltDatabase.db if present). Wait for first valid match type (matchmaking or tourney). Upon result of match, program will attempt to store entry in database, then error will occur.
## Expected behavior
Match expected to be stored in database after result obtained.

## Log:
```
Player 1 chance to win: 50.0%
Current Balance is: $994,072
Bet placed: $1 on player2
Current Tier is: 2
Currently in Matchmaking with 100 matches remaining.  Game state is locked.
True Winstreaks are: (-1, 8)
Currently in Matchmaking with 99 matches remaining.  Game state is 2.
Player 2 wins!
YOU WON THE BET!
Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\saltybot\SaltyBot-main\SaltyStateMachine.py", line 85, in <module>
    recorder.record_match(my_parser.get_p1name(),my_parser.get_p1odds(), my_parser.set_p1winstatus(), my_parser.get_p2name(), my_parser.get_p2odds(), my_parser.set_p2winstatus(), my_socket.adj_p1winstreak, my_socket.adj_p2winstreak, my_socket.adj_p1_tier, my_socket.adj_p2_tier, ratings_to_db[0].mu, ratings_to_db[0].sigma, ratings_to_db[1].mu, ratings_to_db[1].sigma, game_time.snapshot, bettor.outcome, my_parser.is_tourney())
  File "C:\Users\xxx\Downloads\saltybot\SaltyBot-main\SaltyDatabase.py", line 45, in record_match
    self.con.executemany(sql, data)
sqlite3.OperationalError: table SBMATCHES has no column named betOutcome
```

## Notes
Changing [this line](https://github.com/xxxFRIARxxx/SaltyBot/blob/900f9651d0fcdeb2cebc36e7d01b29c1bf69de13/SaltyDatabase.py#L37)
from
`  sql = 'INSERT INTO SBMATCHES (p1name, p1odds, p1win, p1streak, p1mu, p1sigma, p1tier, p1tourney, p1time, p2name, p2odds, p2win, p2streak, p2mu, p2sigma, p2tier, p2tourney, p2time, betOutcome) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
`
to
`
            sql = 'INSERT INTO SBMATCHES (p1name, p1odds, p1win, p1streak, p1mu, p1sigma, p1tier, p1tourney, p1time, p2name, p2odds, p2win, p2streak, p2mu, p2sigma, p2tier, p2tourney, p2time, bet_outcome) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
`
appears to fix this error.

**Comment by xxxFRIARxxx** [comment]
Thank you for so much detail in the error, as well as reproduction and an attempted fix.

I've looked into this, and the error was originally caused by a bad rename on my behalf.  When this program runs for the first time, it creates a database if it doesn't find one already.

I accidentally renamed one of the values in the creation of the database to "bet_outcome" when renaming other things.  Whoops.

I'm renaming it back to "betOutcome", and will be pushing an update as soon as this comment is closed.

Thank you again for your research,
Friar
