### ISSUE TITLE
Program doesn't leave Exhibs if started in Exhibs

### ISSUE THREAD

**Issue by xxxFRIARxxx** [xxxFRIARxxx/SaltyBot#21]
If originally-started while SaltyBet is in Exhibitions, SSM doesn't transition out of Exhibitions to any other game mode.

If it starts in any other game mode, it can move through all of them (including exhibitions) correctly.  

Bug exhibited just when it STARTS in exhibitions.

**Comment by xxxFRIARxxx** [comment]
@zappybiby I just checked, and I'm unable to merge this pull request if created (too many overlapping changes?)

I don't know what to do here to be able to review your code.  I'll ask my friend, but do you have any thoughts?

**Comment by xxxFRIARxxx** [comment]
@zappybiby Manually changed the code in my main.  Testing for a day, then will push to main tomorrow (4/4) if everything works correctly.

Thank you!!

**Comment by xxxFRIARxxx** [comment]
@zappybiby 

This does NOT work if the program is started in Exhibs.  Please check my main to make sure it's what we're looking for?

**Comment by zappybiby** [comment]
What is the output of the program when SB changes to matchmaking mode? 

For reference, here is the output of "alert" and "remaining" keys when SB transitions from exhib to MM. I'm not sure where to look other than is_exhib for this issue.

#### alert, remaining
```
,FINAL ROUND! Stay tuned for exhibitions after the tournament!
Exhibition mode start!,25 exhibition matches left!
,24 exhibition matches left!
,23 exhibition matches left!
,22 exhibition matches left!
,21 exhibition matches left!
,20 exhibition matches left!
,19 exhibition matches left!
,18 exhibition matches left!
,17 exhibition matches left!
,16 exhibition matches left!
,15 exhibition matches left!
,14 exhibition matches left!
,13 exhibition matches left!
,12 exhibition matches left!
,11 exhibition matches left!
,10 exhibition matches left!
,9 exhibition matches left!
,8 exhibition matches left!
,7 exhibition matches left!
,6 exhibition matches left!
,5 exhibition matches left!
,4 exhibition matches left!
,3 exhibition matches left!
,2 exhibition matches left!
,Matchmaking mode will be activated after the next exhibition match!

,100 more matches until the next tournament!
```

**Comment by zappybiby** [comment]
Was able to reproduce bug: https://gist.github.com/zappybiby/82f14fb4e2ea664524303a9519119536

It looks like the remaining value changes to `Matchmaking mode will be activated after the next exhibition match!` at the end of the _second to last_ exhib game result. 

```
ic| SaltyStateMachine.py:48 in <module> at 12:47:01.507
ic| game_mode: 'Matchmaking'
    previous_game_mode: 'Exhibition'
    game_state_lies: True
ic| my_json.get_json(): {'alert': '',
                         'p1name': 'Baby bonnie hood EX3',
                         'p1total': '958,912',
                         'p2name': 'Sasquatch',
                         'p2total': '584,972',
                         'remaining': 'Matchmaking mode will be activated after the next exhibition '
                                      'match!',
                         'status': '1',
                         'x': 1}
```
But, following this match, there is actually one more match following this one (i.e. the _actual_ final exhib match), which has the same remaining value. 

```
ic| SaltyStateMachine.py:48 in <module> at 12:47:08.029
ic| game_mode: 'Exhibition'
    previous_game_mode: 'Matchmaking'
    game_state_lies: True
ic| my_json.get_json(): {'alert': '',
                         'p1name': 'Team A',
                         'p1total': '0',
                         'p2name': 'Team B',
                         'p2total': '0',
                         'remaining': 'Matchmaking mode will be activated after the next exhibition '
                                      'match!',
                         'status': 'open',
                         'x': 0}
```
