### ISSUE TITLE
Feature Request: Use Historic Odds in Kelly Bet Calculation

### ISSUE THREAD

**Issue by zappybiby** [xxxFRIARxxx/SaltyBot#22]
With odds for each player being added to the database, we can use the calculated odds in the Kelly Bet calculation.
Currently the Kelly Bet calculation in SaltyBet assumes odds at 1:1 for every match.

**Example**
```
p1_win_probability = 0.9
p1_odds = 10
p2_odds = 1
total_balance = 10000
# Calculate net odds based on which player is expected to win
if p1_win_probability > 0.5:
    # Calculate average odds for betting on Player1
    net_odds = (p2_odds / p1_odds)
else:
    # Calculate average odds for betting on Player2
    net_odds = (p1_odds / p2_odds)

kelly_criterion = abs(((p1_win_probability * net_odds) - (1 - p1_win_probability)) / net_odds)

# Current KBet Implementation
q = 1 - p1_win_probability
b = 1
fraction = abs(p1_win_probability - (q / b))
print("modified KBet with odds :", kelly_criterion)
print("original SaltyBet KBet: ", fraction)
```
which would output
```
modified KBet with odds : 0.09999999999999967
current SaltyBet KBet:  0.8
```
Without considering odds and given a expected win probability of 90%, SaltyBet would wager 80% of total balance (if we did not limit it to a maximum of 5% of our total balance), whereas KBet with odds would wager about 10%. If we were to consider average odds for a player, we may not need to limit max bets anymore, as the intention of using Kelly Bet is to prevent us from going broke.

**Comment by xxxFRIARxxx** [comment]
@zappybiby haha I'm beating you to the punch again!  👊  (just messing man, all good)

But, in the latest branch (I haven't merged yet, cuz I'm still working on it), I use the historical odds for the projected winner to determine "b" in the Kelly Criterion (what you're describing above).

I don't know if I should use the historical odds-average from the predicted winner, or a DIFFERENCE  between historical odds between the 2 fighters, or what...

Thoughts?

**Comment by xxxFRIARxxx** [comment]
Added feature with #23

**Comment by xxxFRIARxxx** [comment]
@zappybiby Thinking about using "net odds" like you have above instead...give me today to think...

**Comment by zappybiby** [comment]
```
# Kelly Bet Formula: fraction_of_balance = ((b*p)-q))/b
# b is the net odds received on the wager (“b to 1″), p is the probability of winning, q is the probability of losing, which is 1 − p

if p1_probability > 0.5:
    b = p1_odds_avg
    q = 1 - p1_probability
    p = p1_probability
elif p1_probability < 0.5:
    b = p2_odds_avg
    q = p1_probability
    p = abs(p1_probability-1)

fraction = ((p*b)-q)/b
        max_bet_percentage = .05
        k_suggest = max_bet_percentage*(fraction*balance)

...

elif (predicted_winner != None) and (game_mode != "Tournament"):
            if p1_probability != .5 and fraction > 0: # if fraction < 0, kelly bet advises not placing a bet on this match
                self.suggested_wager = decimal.Decimal(k_suggest).quantize(decimal.Decimal('0'), rounding=decimal.ROUND_UP)
```

**Comment by zappybiby** [comment]
Fixed in https://github.com/xxxFRIARxxx/SaltyBot/pull/28
