### ISSUE TITLE
Error in Calculation of Kelly Bet Criterion

### ISSUE THREAD

**Issue by zappybiby** [xxxFRIARxxx/SaltyBot#27]
SaltyBot currently restricts the total balance that can be bet through the Kelly Bet Formula. I found this unusual because the Kelly bet strategy is designed to prevent gamblers from going broke and normally shouldn't have any additional limit imposed on it. Typically, using either the kelly bet criterion or the maximum fraction of your total balance as a betting strategy would be two separate strategies, not something used together. The Kelly Bet Criterion should not require a maximum limit by design. 

SaltyBot's current implementation of the Kelly Bet Criterion seems to go broke quickly without a limit with a >50% overall successful bet rate. I believe this is likely due to an error in the way SaltyBot formats odds. 

The average odds are given to the Kelly equation as a decimal, such as 2.5. In our case, this means that for every $2.5 bet, $1 is earned. However, I believe the equation assumes 2.5 is in the format A/B, where every value of B that you bet, you will win A, plus the return of your stake. However, the odds calculated in SaltyBet are formatted in the reverse manner, B/A.

Taking a look at the kelly bet criterion equation:
```
fraction = ((b * p) - q) / b == ((odds * win_prob) - (1 - win_prob)) / (odds)
```
In this equation, plugging in a balance of $1000, odds 2.5, and probability of 0.55 (55%) would output a fraction of 0.37, or $370. But this bet is objectively bad -- the odds are against us given the slight edge of winning, raising questions as to why we would want to bet almost 40% of our balance on this single match. 

If we instead divide 1 over the odds, i.e. 1/2.5, to match the A/B odds format, the Kelly Bet fraction becomes negative,  -0.574, indicating that it does not recommend betting on this match due to unfavorable returns

Looking at this [online Kelly Bet calculator](https://dqydj.com/kelly-criterion-bet-calculator/), the example odds it provides are "2 to 1 odds", or odds = 2. However, the example states that in this example "The casino is willing to pay 2 to 1 on any bet you make", which follows the A/B odds format mentioned above. This gives support to my theory that we are formatting odds wrong for the Kelly Bet Equation.

**Comment by xxxFRIARxxx** [comment]
@zappybiby Do you have discord?

**Comment by zappybiby** [comment]
> @zappybiby Do you have discord?

Pastebin: https://pastebin.com/gv6Rb6Dh 
password is your public username on SaltyBet.com. Expires in 1 week.

**Comment by xxxFRIARxxx** [comment]
@zappybiby Just sent a request.
