### ISSUE TITLE
Program bets using the developer's account

### ISSUE THREAD

**Issue by zappybiby** [xxxFRIARxxx/SaltyBot#3]
## Describe the bug
It appears that the program is betting with the developer's SaltyBet account. I discovered this as the balance the program thought I had was not correct. My actual balance was $10,000 but was instead showing $1,000,000. Upon debugging, it appears BeautifulSoup is returning the balance and leaderboard information from a username associated with the developer's account instead of the account provided credentials in the .env file. 

## To Reproduce
Enter required credentials in .env file and start SaltyStateMachine.py

## Expected behavior
Program should pull balance from account provided in the .env file.

## Notes
This appears to be an issue with the provided cookies in `SaltyWebInteractor.py`. Changing the cookie `PHPSESSID` in both the cookies and header dicts to the stored cookies in my browser seems to correct this issue.

Currently looking at [this](https://stackoverflow.com/a/42436962) for implementation. Only the user agent is needed to be provided initially, then the remainder of headers/cookies can be accessed dynamically.

**Comment by xxxFRIARxxx** [comment]
It looks like I can't pull "PHPSESSID" out of cookies, as it's not provided upon login.  (That I can see)

**Comment by xxxFRIARxxx** [comment]
This has been fixed.  Please let me know if I've overlooked anything else relating to this issue, or anything else that comes up.

Thank you for the report!
