### ISSUE TITLE
Last match of tournament isn't recording

### ISSUE THREAD

**Issue by zappybiby** [xxxFRIARxxx/SaltyBot#4]
**Describe the bug**
The result of the last match of the tournament isn't being recorded. This is a known issue as mentioned on the README / code TODO, but I just wanted to make it an official issue for discussion to fix it.

**Log**
I added print statements that output when `game_state != previous_game_state` or `game_mode != previous_game_mode`
```
Currently in Tournament with 1 matches remaining.  Game state is open.
Player 1 chance to win: 54.34%
Current Balance is: $25,421
Bet placed: $11 on player1
Current Tier is: 2
game_state != previous_game_state //  game_state_lies = False  // state locked // prev state open
Currently in Tournament with 1 matches remaining.  Game state is locked.
True Streaks are: (3, 5)
game_mode != previous_game_mode // game_state_lies = True // current mode: Exhibition // prev mode: Tournament
game_state != previous_game_state // game_state_lies = False // state 1 // prev state locked
In Exhibition.  No bets are placed, and nothing is recorded.  25 matches left.
```
**Notes**
I think what might be causing this is that the game mode is being updated (From Tournament -> Exhibitions) before (or at the same time) the match result is detected (Game State: locked -> 1). The program is correctly detecting that player 1 won (game_state = 1), but because the game mode changed, the [if statement ](https://github.com/xxxFRIARxxx/SaltyBot/blob/52e7bbbbd0d5b52c3723201dc2368b56f3a8169f/SaltyStateMachine.py#L47) detects that Exhibitions mode is active and instead logic proceeds to this [elif statement](https://github.com/xxxFRIARxxx/SaltyBot/blob/52e7bbbbd0d5b52c3723201dc2368b56f3a8169f/SaltyStateMachine.py#L80). As a result, the program will not record the match.

Unsure if it helps, but here is what the twitch chatbot WAIFU4u posts in the following order when the last match of the tournament ends:
```
WAIFU4u: Exhibitions will start shortly. Thanks for watching!
WAIFU4u: Chopper wins! Payouts to Team Red. 25 exhibition matches left!
WAIFU4u: Bets are OPEN for Koumakan sakuya vs Haizilyo! (S Tier) (Requested by Lookbeneathyou) (exhibitions) 
```

**Comment by xxxFRIARxxx** [comment]
Thank you for documenting this officially outside of the #TODO in the program itself.

Yes, you're correct in that the way that the JSON updates, it updates the game mode first, then the game state.  Because of this, we're in the "no last match of tournies recording" issue here.

Fix incoming probably later this week.

Keep 'em coming if you find them.

**Comment by xxxFRIARxxx** [comment]
This should now be fixed!  

Please let me know if it isn't, and I'll reopen.
