### ISSUE TITLE
Check if .env file exists / provide feedback if login fails

### ISSUE THREAD

**Issue by zappybiby** [xxxFRIARxxx/SaltyBot#6]
**Is your feature request related to a problem? Please describe.**
- SaltyBot does not currently check to see if .env file is in the project directory. If the .env file is not provided, the program will continue with the email and password environment variables set as `'None'`. The program will fail to login, but does not communicate this to the end user.
- Currently, the only hint to the user that the program isn't functioning is the following alert: `Either winstreaks or tier didn't retrieve from Twitch.  This match wasn't recorded` which comes from the `record_match` function in `SaltyDatabase.py`.
- Adding a check for the .env file would be beneficial as it is necessary for the program to save matches and would it clearer to the end user why the program might be failing to retrieve info from Twitch.

**Describe the solution you'd like**
Use conditional statement that checks if dotenv's `find_dotenv` function returns True to verify .env file exists in project directory.

**Other Considerations**
Given that the functionality of the program to save matches is critical for it to make any bets, and the lack of an .env file renders it unable to do this, we may want it throw an exception / stop the program if .env file is not detected. In my PR I will add below, the program doesn't stop or throw an exception if the .env file is not found, rather it will just print to the console that it was not detected and to read README for instructions.

**Comment by xxxFRIARxxx** [comment]
Closed with pull.  Thanks for the work!  (PS:  let me know if the JSON error is still happening for you)
